name       : perl-variable-magic
version    : '0.63'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/V/VP/VPIT/Variable-Magic-0.63.tar.gz : ba4083b2c31ff2694f2371333d554c826aaf24b4d98d03e48b5b4a43a2a0e679
homepage   : https://metacpan.org/pod/Variable::Magic
license    : Artistic-2.0
component  : programming.python
summary    : Variable::Magic - Associate user-defined magic to variables from Perl
description: |
    Magic is Perl's way of enhancing variables. This mechanism lets the user add extra data to any variable and hook syntactical operations (such as access, assignment or destruction) that can be applied to it. With this module, you can add your own magic to any variable without having to write a single line of XS.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
