name       : perl-variable-magic
version    : '0.62'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/V/VP/VPIT/Variable-Magic-0.62.tar.gz : 3f9a18517e33f006a9c2fc4f43f01b54abfe6ff2eae7322424f31069296b615c
license    : Artistic-2.0
component  : programming.python
summary    : Associate user-defined magic to variables from Perl
description: |
    Associate user-defined magic to variables from Perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
