name       : perl-variable-magic
version    : 0.61
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/V/VP/VPIT/Variable-Magic-0.61.tar.gz : b8afe92e54c72a2ed2ca1b08ce90518b855734f7d33c454d0f66f2c1ccf8a6d7
license    : Artistic-2.0
component  : programming.python
summary    : Associate user-defined magic to variables from Perl
description: |
    Associate user-defined magic to variables from Perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
